### PR TITLE
chore: enable dependabot and CodeQL

### PR DESCRIPTION
**Pull request by apeabody**
---TEST---

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by apeabody** [comment]
FYI: https://github.com/ossf/scorecard-action/issues/109

**Comment by apeabody** [comment]
https://github.com/ossf/scorecard-action/issues/248

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_headers
 All files need a license header. Please make sure all your files include the appropriate header. A helper tool available [here](https://github.com/google/addlicense). 
 ```bash 
Checking file headers
./.github/workflows/codeql.yml
./.github/dependabot.yml
 ```

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request closed without merging**
